// de
define({
    yes: "Ja",
    no: "Nein",
    apply: "Übernehmen",
    cancel: "Abbrechen",
    general: "Allgemein",
    settings: "Einstellungen",
    logs: "Protokoll",
    info: "Informationen",
    services: "Dienste",
    service: "Dienst",
    newService: "Neuer Dienst",
    deleteServiceId: "Dienst '${id}' entfernen",
    deleteServiceMessage: "Möchten Sie den Dienst '${id}' wirklich entfernen?",
    deleteServiceSuccess: "Der Dienst '${id}' wurde erfolgreich entfernt.",
    startingService: "Der Dienst '${id}' wird gestartet.",
    stoppingService: "Der Dienst '${id}' wird angehalten.",
    startService: "Den Dienst '${id}' starten",
    stopService: "Den Dienst '${id}' anhalten",
    startServiceSuccess: "Der Dienst '${id}' wurde erfolgreich gestartet.",
    stopServiceSuccess: "Der Dienst '${id}' wurde erfolgreich angehalten.",
    startServiceFail: "Beim Starten des Dienstes '${id}' trat ein Fehler auf. Details finden Sie in der Protokolldatei.",
    stopServiceFail: "Beim Anhalten des Dienstes '${id}' trat ein Fehler auf. Details finden Sie in der Protokolldatei.",
    browse: "Dienst-URL anzeigen",
    viewInMapApps: "In map.apps anzeigen",
    edit: "Bearbeiten",
    delete: "Löschen",
    id: "Id",
    name: "Name",
    type: "Typ",
    description: "Beschreibung",
    copyright: "Copyright",
    saveServiceSuccess: "Die Änderungen am Dienst '${id}' wurden erfolgreich gespeichert.",
    saveServiceFail: "Beim Speichern des Dienstes '${id}' trat ein Fehler auf. Details finden Sie in der Protokolldatei.",
    editSecuritySettings: "Sicherheit für Dienst '${name}' einstellen",
    public: "Öffentlich, für alle sichtbar",
    private: "Privat, allen angemeldeten Benutzern Zugriff gewähren",
    privateForGroups: "Privat, allen Benutzern aus den ausgewählten Gruppen Zugriff gewähren",
    groups: "Gruppen",
    groupsAllowed: "Gruppen denen der Zugriff erlaubt ist",
    search: "Suche",
    refresh: "Neuladen",
    reset: "Zurücksetzen",
    time: "Zeit",
    message: "Meldung",
    security: "Sicherheit einstellen"
});