when:
  event: [tag]

steps:

  build:
    image: eclipse-temurin:17@sha256:068a8f9ae4b74d9a20de3ecca771ba1a6437f1d7a8a8ad6deaf9dbdd2274397a
    commands:
      - export GRADLE_USER_HOME=$${DRONE_WORKSPACE}/.gradle
      - ./gradlew check assemble -Prelease=true -PdeployUser=$SNAPSHOT_USER -PdeployPassword=$SNAPSHOT_PASS
    secrets: [ snapshot_user, snapshot_pass]

  publish:
    image: eclipse-temurin:17@sha256:068a8f9ae4b74d9a20de3ecca771ba1a6437f1d7a8a8ad6deaf9dbdd2274397a
    commands:
      - export GRADLE_USER_HOME=$${DRONE_WORKSPACE}/.gradle
      - ./gradlew publish -Prelease=true -PdeployUser=$SNAPSHOT_USER -PdeployPassword=$SNAPSHOT_PASS
    secrets: [ snapshot_user, snapshot_pass]
