define({
    root: {
        yes: "Yes",
        no: "No",
        apply: "Apply",
        cancel: "Cancel",
        ok: "OK",
        general: "General",
        settings: "Settings",
        logs: "Logs",
        info: "Info",
        services: "Services",
        service: "Service",
        newService: "New Service",
        deleteServiceId: "Delete service '${id}'",
        deleteServiceMessage: "Do you really want to delete the service '${id}'?",
        deleteServiceSuccess: "Deleted service '${id}' successfully",
        startingService: "Starting service '${id}'",
        stoppingService: "Stopping service '${id}'",
        startService: "Start service '${id}'",
        stopService: "Stop service '${id}'",
        startServiceSuccess: "Started service '${id}' successfully",
        stopServiceSuccess: "Stopped service '${id}' successfully",
        startServiceFail: "Failure when starting service '${id}'. See log file for details.",
        stopServiceFail: "Failure when stopping service '${id}'. See log file for details.",
        browse: "Browse service URL",
        viewInMapApps: "View in map.apps",
        edit: "Edit",
        delete: "Delete",
        id: "Id",
        name: "Name",
        type: "Type",
        description: "Description",
        saveServiceSuccess: "Saved changes for service '${id}' successfully",
        saveServiceFail: "Saving changes for service '${id}' failed. See log file for details.",
        editSecuritySettings: "Edit security settings for service '${name}'",
        public: "Public, visible to all",
        private: "Private, grant access to all logged in users",
        privateForGroups: "Private for users in selected groups",
        groups: "Groups",
        groupsAllowed: "Groups allowed to access this service",
        search: "Search",
        refresh: "Refresh",
        reset: "Reset",
        time: "Time",
        message: "Message",
        security: "Edit Security"
    },
    "de": true
});